[package]
org= "ballerina"
name= "openapi"
version= "0.9.0-beta.6"

[[platform.java11.dependency]]
path = "../openapi-validator/build/libs/openapi-validator-0.9.0-beta.6-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "openapi"
version = "0.9.0-beta.6-SNAPSHOT"
