[package]
org= "ballerina"
name= "openapi"
version= "2.0.11"

[[platform.java11.dependency]]
path = "../openapi-validator/build/libs/openapi-validator-2.0.11.jar"
groupId = "ballerina"
artifactId = "openapi"
version = "2.0.11"
