[package]
org= "ballerina"
name= "openapi"
version= "0.9.0-beta.1"

[[platform.java11.dependency]]
path = "../openapi-validator/build/libs/openapi-validator-@project.version@.jar"
groupId = "ballerina"
artifactId = "openapi"
version = "@project.version@"
