[package]
org= "ballerina"
name= "openapi"
version= "1.0.3"

[[platform.java11.dependency]]
path = "../openapi-validator/build/libs/openapi-validator-1.0.3-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "openapi"
version = "1.0.3-SNAPSHOT"
