[project]
org-name = "ballerina"
version = "1.0.1"

[dependencies]
"ballerina/io" = "0.5.1"
"ballerina/log" = "1.0.1"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "openapi"
    version = "1.0.1-SNAPSHOT"
    path = "../openapi-validator/build/libs/openapi-validator-1.0.1-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["openapi"]
