[package]
org= "ballerina"
name= "openapi"
version= "2.0.0"

[build-options]
observability-included=true

[[platform.java11.dependency]]
path = "../openapi-validator/build/libs/openapi-validator-2.0.0-Preview6-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "openapi"
version = "2.0.0-Preview6-SNAPSHOT"
