[plugin]
id = "ballerina-openapi"
class = "io.ballerina.openapi.validator.OpenAPIValidatorPlugin"

[[dependency]]
path = "../openapi-validator/build/libs/openapi-validator-@project.version@.jar"
groupId = "ballerina"
artifactId = "openapi"
version = "@project.version@"
