[plugin]
id = "ballerina-openapi"
class = "org.ballerinalang.openapi.validator.OpenAPIValidatorPlugin"

[[dependency]]
path = "../openapi-validator/build/libs/openapi-validator-2.0.11.jar"
groupId = "ballerina"
artifactId = "openapi"
version = "2.0.11"
